"""empty message

Revision ID: 427a455e558b
Revises: 
Create Date: 2023-11-30 19:21:12.716332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427a455e558b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('firstName', sa.String(length=500), nullable=True),
    sa.Column('lastName', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=500), nullable=True),
    sa.Column('password', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('houseNumName', sa.String(length=500), nullable=True),
    sa.Column('street', sa.String(length=500), nullable=True),
    sa.Column('town', sa.String(length=500), nullable=True),
    sa.Column('postcode', sa.String(length=7), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('basket',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('orderID', sa.Integer(), nullable=True),
    sa.Column('addressID', sa.Integer(), nullable=True),
    sa.Column('orderDate', sa.DateTime(), nullable=True),
    sa.Column('productID', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('totalOrderCost', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=True),
    sa.Column('imageName', sa.String(length=500), nullable=True),
    sa.Column('imageAlt', sa.String(length=500), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tagName', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('productTags',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'tag_id')
    )
    op.create_table('userAddresses',
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ),
    sa.PrimaryKeyConstraint('address_id', 'account_id')
    )
    op.create_table('userBasket',
    sa.Column('basket_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['basket_id'], ['basket.id'], ),
    sa.PrimaryKeyConstraint('basket_id', 'account_id')
    )
    op.create_table('userOrders',
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('order_id', 'account_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('userOrders')
    op.drop_table('userBasket')
    op.drop_table('userAddresses')
    op.drop_table('productTags')
    op.drop_table('tags')
    op.drop_table('products')
    op.drop_table('orders')
    op.drop_table('basket')
    op.drop_table('addresses')
    op.drop_table('accounts')
    # ### end Alembic commands ###
